name: Test Code
on: workflow_dispatch

jobs:

  e2e_tests:
    name: SQL Server Test
    runs-on: ubuntu-latest
    steps:
      - name: Install SQL Server
        uses: Particular/install-sql-server-action@main
        with:
          connection-string-env-var: DATABASE_URL
          catalog: seagen
          extra-params: 'integratedSecurity=true;trustServerCertificate=true;'

      - name: What's the connection string?
        run: echo "DATABASE_URL - $DATABASE_URL"
